#!/bin/bash
#usage: $ ./ITGDecALL
#
# This script will take all log files (name starting with 'log_')
# and decode them.
#
# after putting them nicely in a folder here...
# ... they will also be scp'd to 141.13.92.12.
#
############################################
#DECODE
sudo rm -rf /home/mininet/itg-logs/
for file in $(ls log_*)
do
    outputFileName="decoded_txt_${file}.txt"
    outputOctaveFileName="decoded_dat_${file}.dat"
    sudo ~/D-ITG/D-ITG-2.8.0-rc1/bin/ITGDec ${file} -l $outputFileName -o $outputOctaveFileName
done

mkdir itg-logs
mv decoded_* itg-logs

touch itg-logs/complete.dat

#for file in $(ls /home/mininet/itg-logs/decoded_*.txt | tac)
#do
    #echo "${file}"
    #cat "${file}" >> /home/mininet/itg-logs/complete.txt
#done
#for file in $(ls /home/mininet/itg-logs/decoded_*.dat | tac)
#do
    #echo "${file}"
    #cat "${file}" >> /home/mininet/itg-logs/complete.dat
#done

sshpass -p tcpip-admin ssh -oStrictHostKeyChecking=no ktr@141.13.92.12 "rm -rf Documents/MATLAB/Mininet/itg-logs && mkdir Documents/MATLAB/Mininet/itg-logs && exit"
sshpass -p tcpip-admin scp -oStrictHostKeyChecking=no -r itg-logs/* ktr@141.13.92.12:Documents/MATLAB/Mininet/itg-logs/
