#!/bin/bash
#usage: $ ./ITGSendUDP 10.0.0.x <number>
#
#       <number> is for enumerating the logs
#
#   -a  dest ip
#   -rp rcv port (9500)
#       -sp src port (9400)
#
#   -T  protocol type
#
#   -C  packets/sec
#   -c  packtsize <constant>
#   -t  duration in microsec
#
#   -l  send_log_file
#   -L  logserv ip
#   -x  recv_log_file
#   -X  logserv ip
#
############################################
#GENERATE LOGFILENAMES
sendname="log_snd_${2}"
recvname="log_rcv_${2}"
logserv="${3}"
#logserv="<insert ip here>"
#
#GO TEST SOME STUFF
sudo D-ITG/D-ITG-2.8.0-rc1/bin/ITGSend -a "$1" -rp 9500 -T UDP -C 100 -c 25 -t 60000 -l $sendname -L $logserv -x $recvname -X $logserv
