#!/bin/bash
#
#usage: $ ./ITGSendTCP_cbr <recv ip> <logserv ip> <bitrate> <duration>
#       <ip> is in the 10.0.0.x range
#       <duration> 1000 is 1 sec
#
#   -a  dest ip
#   -rp rcv port (9500)
#       -sp src port (9400)
#
#   -T  protocol type
#
#   -C  packets/sec
#   -c  packtsize <constant> in bytes
#       UDP: 1500 - 20 - 8 =  1472
#       TCP: 1500 - 20 - 20 = 1460
#
#   -u  min .. max packetsize <variable>
#   -t  duration in milisec
#
#   -l  send_log_file
#   -L  logserv ip
#   -x  recv_log_file
#   -X  logserv ip
#
############################################
#DESTINATIONS
destserv="${1}"
logserv="${2}"
#GENERATE LOGFILENAMES
sendname="log_tcp_snd_${3}_cbr"
recvname="log_tcp_rcv_${3}cbr"
#TRAFFIC
bitrate=1460
duration="${4}"
packetcount="${5}"
#
#GO TEST SOME STUFF
sudo D-ITG/D-ITG-2.8.0-rc1/bin/ITGSend -a $destserv -rp 9500 -T TCP -C $packetcount -c $bitrate -t $duration -l $sendname -L $logserv -x $recvname -X $logserv
