#!/bin/bash
#
#usage: $ ./ITGSendUDP_cbr <recv ip> <logserv ip> <bitrate> <duration>
#       <ip> is in the 10.0.0.x range
#       <id> is for enumerating the logs
#
#   -a  dest ip
#   -rp rcv port (9500)
#       -sp src port (9400)
#
#   -T  protocol type
#
#   -C  packets/sec
#   -c  packtsize <constant>
#   -u  min .. max packetsize <variable>
#   -t  duration in microsec
#
#   -l  send_log_file
#   -L  logserv ip
#   -x  recv_log_file
#   -X  logserv ip
#
############################################
#GENERATE LOGFILENAMES
destserv="${1}"
logserv="${2}"
sendname="log_snd_udp_${3}cbr"
recvname="log_rcv_udp_${3}cbr"
bitrate="${3}"
duration="${4}"
#
#GO TEST SOME STUFF
sudo D-ITG/D-ITG-2.8.0-rc1/bin/ITGSend -a $destserv -rp 9500 -T UDP -C 100 -c $bitrate -t $duration -l $sendname -L $logserv -x $recvname -X $logserv
